$TTL @UPDATE_INTERVAL@
;
; dns zone for for schroder.net
;
; any time you make a change to the domain, bump the
; "serial" setting below. the format is easy:
; YYYYMMDDI, with the I being an iterator in case you
; make more than one change during any one day
$ORIGIN cs559.gr.
@ IN SOA ns1.cs559.gr. admin.cs559.gr. (
                        201205026 ; serial
                        8h        ; refresh
                        4h        ; retry
                        4w        ; expire
                        1d )      ; minimum
	IN NS ns1.cs559.gr.
	IN NS ns2.cs559.gr.

;cs559.gr IN A 192.168.14.254 
ns1	IN A @MY_IP@
ns2	IN A @MY_IP@
team1	IN A 192.168.14.0
	 	IN A 192.168.14.1
	 	IN A 192.168.14.2
	 	IN A 192.168.14.3
	 	IN A 192.168.14.4
	 	IN A 192.168.14.5
	 	IN A 192.168.14.6
	 	IN A 192.168.14.7
team3 	IN A 192.168.14.10
	 	IN A 192.168.14.11
	 	IN A 192.168.14.12
	 	IN A 192.168.14.13
	 	IN A 192.168.14.14
	 	IN A 192.168.14.15
